FROM docker.io/library/ubuntu:20.04 AS ubuntu-sudo-and-nix-install-deps

#  && apt-get remove -y sudo \
RUN apt-get update \
 && apt-get install --no-install-recommends --no-install-suggests -y \
    ca-certificates \
    curl \
    tar \
    sudo \
    xz-utils \
 && apt-get -y autoremove \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*

RUN addgroup nixgroup \
 && adduser \
    --quiet \
    --disabled-password \
    --shell /bin/bash \
    --home /home/nixuser \
    --gecos "User" nixuser \
    --ingroup nixgroup \
 && usermod -a -G sudo nixuser \
 && echo "nixuser:123" | chpasswd \
 && echo 'nixuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
 && chmod 0700 /home/nixuser \
 && mkdir -p /home/nixuser/tmp \
 && chown -R nixuser: /home/nixuser/tmp

USER nixuser

ENV USER nixuser
ENV HOME /home/nixuser

WORKDIR /home/nixuser


FROM docker.io/library/ubuntu:20.04 AS ubuntu-and-nix-install-deps


RUN apt-get update \
 && apt-get install --no-install-recommends --no-install-suggests -y \
    ca-certificates \
    curl \
    tar \
    xz-utils \
 && apt-get remove -y sudo \
 && apt-get -y autoremove \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*

RUN addgroup nixgroup \
 && adduser \
    --quiet \
    --disabled-password \
    --shell /bin/bash \
    --home /home/nixuser \
    --gecos "User" nixuser \
    --ingroup nixgroup \
 && usermod -a -G sudo nixuser \
 && echo "nixuser:123" | chpasswd \
 && echo 'nixuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
 && chmod 0700 /home/nixuser \
 && mkdir -p /home/nixuser/tmp \
 && chown -R nixuser: /home/nixuser/tmp

USER nixuser

ENV USER nixuser
ENV HOME /home/nixuser

WORKDIR /home/nixuser

# sh <(curl -L https://releases.nixos.org/nix/nix-2.10.1/install) --no-daemon
# curl -L https://releases.nixos.org/nix/nix-2.10.1/install | sh -s -- --no-daemon